# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "Panoround" do

pod 'JSONModel'
pod 'SDWebImage', '~>3.6'
pod 'Google-Maps-iOS-SDK', '~> 1.9.1'

end

target "PanoroundTests" do

end
